apiVersion: v1
kind: Pod
metadata:
  name: non-root
spec:
  securityContext:
    runAsUser: 2046
    runAsGroup: 2046
    fsGroup: 2046
  containers:
  - name: non-root
    image: gcr.io/vinaygo-gke-dev/konnectivity-server:v1.0.0
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /etc/srv/kubernetes/konnectivity-server
      name: uds
  volumes:
  - name: uds
    hostPath:
      path: /etc/srv/kubernetes/konnectivity-server
      type: DirectoryOrCreate
