apiVersion: v1
kind: Pod
metadata:
  name: non-root-init
spec:
  containers:
  - name: non-root-init
    image: ubuntu
    securityContext:
      runAsUser: 0
      runAsGroup: 0
    command:
    - "/bin/bash"
    - "-c"
    - |-
      chown 0:0 /etc/srv/kubernetes/konnectivity-server
      if [[ -f /etc/srv/kubernetes/konnectivity-server/konnectivity-server.socket ]]; then
        rm /etc/srv/kubernetes/konnectivity-server/konnectivity-server.socket
      fi
    volumeMounts:
    - mountPath: /etc/srv/kubernetes/konnectivity-server
      name: uds
  volumes:
  - name: uds
    hostPath:
      path: /etc/srv/kubernetes/konnectivity-server
      type: DirectoryOrCreate
  