apiVersion: v1
kind: Pod
metadata:
  name: pod-non-root-caps
spec:
  containers:
  - name: server
    image: gcr.io/vinaygo-gke-dev/simpleserver:v1.0.0
    imagePullPolicy: Always
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      capabilities:
        drop:
        - ALL
        add:
        - NET_BIND_SERVICE
    command:
    - ./server
    - --port 80
