apiVersion: v1
kind: Pod
metadata:
  name: pod-non-root-filecaps
spec:
  containers:
  - name: server
    image: gcr.io/vinaygo-gke-dev/simpleserver:v2.0.0
    imagePullPolicy: Always
    securityContext:
      runAsUser: 1337
      runAsGroup: 1337
      capabilities:
        drop:
        - ALL
        add:
        - NET_BIND_SERVICE
    command:
    - server
    - --port 80
