apiVersion: v1
kind: Pod
metadata:
  name: pod-non-root
spec:
  containers:
  - name: server
    image: gcr.io/vinaygo-gke-dev/simpleserver:v1.0.0
    imagePullPolicy: Always
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
    command:
    - ./server
    - --port 80
