apiVersion: v1
kind: Pod
metadata:
  name: pod-non-root-caps
spec:
  containers:
  - name: coredns
    image: gcr.io/vinaygo-gke-dev/coredns:v1.0.0
    imagePullPolicy: Always
    securityContext:
      runAsUser: 2004
      runAsGroup: 2004
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
        add:
        - NET_BIND_SERVICE
    command:
    - ./coredns
